name: 'update'
on:
  schedule:
    - cron: '25 5,17 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
        - name: 'Update Chrome'
          run: |
            brew reinstall --cask google-chrome
        - name: 'Install requirements'
          run: |
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
        - name: 'run'
          env:
            USER_ID: ${{ secrets.USER_ID }}
            PASS_WD: ${{ secrets.PASS_WD }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            SITE_TYPE: 1
          run: |
            wget -qO run.py "$URL"
            python3 ./run.py
        - name: Delete workflow runs
          uses: Mattraks/delete-workflow-runs@main
          with:
            retain_days: 1
            keep_minimum_runs: 8 
