name: 'update42'
on:
  schedule:
    - cron: "39 3 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: 42
jobs:
  build:
    runs-on: macos-12
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
        - name: 'Update Chrome'
          run: |
            brew reinstall --cask google-chrome
        - name: 'Install requirements'
          run: |
            pip3 install -r ./requirements.txt
            pip3 install undetected-chromedriver
            yes | pip3 uninstall selenium
            pip3 install selenium==4.2.0
        - name: 'run'
          env:
            URL: ${{ secrets.URL }}
            USER_ID: ${{ secrets.USER_ID3 }}
            PASS_WD: ${{ secrets.PASS_WD }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            SITE_TYPE: 3
          run: |
            wget -qO run.py "$URL"
            python3 ./run.py
