name: update
on:
  workflow_dispatch:
  schedule:
    - cron: "5 6 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: update
        run: |
          cat /proc/sys/kernel/random/uuid > uuid.txt
          git config --global user.email action@github.com
          git config --global user.name action
          git add .
          git commit -m "update cron" -a        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_PUSH_TOKEN }}
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
